import type { SurveyDefinition, ChoiceOption, MatrixColumn } from "../types";

function yesNo(): ChoiceOption[] {
  return [
    { value: "yes", label: "Yes" },
    { value: "no", label: "No", terminatesSurvey: true },
  ];
}

function yesNoNotSure(extra: ChoiceOption[] = []): ChoiceOption[] {
  return [{ value: "yes", label: "Yes" }, { value: "no", label: "No" }, { value: "not_sure", label: "Not sure" }, ...extra];
}

const PREFER_NOT_TO_ANSWER: ChoiceOption = { value: "prefer_not_to_answer", label: "Prefer not to answer" };
const OTHER_OPTION: ChoiceOption = { value: "other", label: "Other", allowOther: true };

const AGREE_COLUMNS_WITH_NA: MatrixColumn[] = [
  { value: "strongly_disagree", label: "Strongly disagree" },
  { value: "disagree", label: "Disagree" },
  { value: "neither", label: "Neither agree nor disagree" },
  { value: "agree", label: "Agree" },
  { value: "strongly_agree", label: "Strongly agree" },
  { value: "not_applicable", label: "Not applicable" },
];

const AGREE_COLUMNS: MatrixColumn[] = [
  { value: "strongly_disagree", label: "Strongly disagree" },
  { value: "disagree", label: "Disagree" },
  { value: "neither", label: "Neither agree nor disagree" },
  { value: "agree", label: "Agree" },
  { value: "strongly_agree", label: "Strongly agree" },
];

const FREQUENCY_COLUMNS: MatrixColumn[] = [
  { value: "never", label: "Never" },
  { value: "rarely", label: "Rarely" },
  { value: "sometimes", label: "Sometimes" },
  { value: "often", label: "Often" },
  { value: "very_often", label: "Very often" },
];

const FREQUENCY_COLUMNS_WITH_NOT_SURE: MatrixColumn[] = [...FREQUENCY_COLUMNS, { value: "not_sure", label: "Not sure" }];

export const facebookHoniara2026: SurveyDefinition = {
  slug: "facebook-honiara-2026",
  title: "The State of Facebook Use in Honiara 2026",
  version: "1.0.0",
  estimatedMinutes: 15,
  introText: [
    "Tagio tumas for agreeing to participate in this survey.",
    "This questionnaire asks about your use of Facebook and its relationship with business, tourism, government communication and community wellbeing in Honiara.",
    "The survey should take approximately 10–15 minutes.",
    "Please select the answer that best represents your experience or view. There are no right or wrong answers. You may select “Prefer not to answer” or skip any question that makes you uncomfortable.",
    "Please do not record your name or include information that could identify another person.",
  ],
  screenOutText: [
    "Thank you for your time. Based on your answers, you are not eligible to continue with this survey.",
    "No further information will be collected from you.",
  ],
  thankYouText: [
    "Tagio tumas for completing this survey.",
    "Your responses will be combined with those of other participants and used to better understand Facebook use in Honiara.",
  ],
  sections: [
    {
      id: "admin",
      title: "Collection Details",
      description: "Completed by the student researcher before handing the device to the participant, or while reading questions aloud.",
      questions: [
        {
          code: "ADMIN_PARTICIPANT_CODE",
          type: "text",
          label: "Participant code",
          required: true,
          readOnly: true,
          prefillFrom: "participantCode",
        },
        {
          code: "ADMIN_STUDENT_ID",
          type: "text",
          label: "Student researcher ID",
          required: true,
          readOnly: true,
          prefillFrom: "studentCode",
        },
        {
          code: "ADMIN_DATE",
          type: "text",
          label: "Date of survey",
          required: true,
          readOnly: true,
          prefillFrom: "today",
        },
        {
          code: "ADMIN_AREA",
          type: "single_choice",
          label: "General collection area",
          required: true,
          options: [
            { value: "honiara_east", label: "Honiara East" },
            { value: "honiara_central", label: "Honiara Central" },
            { value: "honiara_west", label: "Honiara West" },
            { value: "other", label: "Other approved location", allowOther: true },
          ],
        },
        {
          code: "ADMIN_MODE",
          type: "single_choice",
          label: "Mode of completion",
          required: true,
          options: [
            { value: "self", label: "Participant completed independently" },
            { value: "researcher_read", label: "Researcher read the questions to the participant" },
            { value: "other", label: "Other approved method", allowOther: true },
          ],
        },
      ],
    },
    {
      id: "A",
      title: "Section A: Eligibility",
      questions: [
        { code: "A1", type: "single_choice", label: "Are you 18 years of age or older?", required: true, options: yesNo() },
        { code: "A2", type: "single_choice", label: "Do you currently use Facebook?", required: true, options: yesNo() },
        { code: "A3", type: "single_choice", label: "Do you currently live, work or study in Honiara?", required: true, options: yesNo() },
        {
          code: "A4",
          type: "single_choice",
          label: "Have you received the Participant Information Sheet and freely agreed to participate?",
          required: true,
          options: yesNo(),
        },
      ],
    },
    {
      id: "B",
      title: "Section B: General Information",
      questions: [
        {
          code: "B1",
          type: "single_choice",
          label: "What is your age group?",
          required: true,
          options: [
            { value: "18_24", label: "18–24 years" },
            { value: "25_34", label: "25–34 years" },
            { value: "35_44", label: "35–44 years" },
            { value: "45_54", label: "45–54 years" },
            { value: "55_64", label: "55–64 years" },
            { value: "65_plus", label: "65 years or older" },
            PREFER_NOT_TO_ANSWER,
          ],
        },
        {
          code: "B2",
          type: "single_choice",
          label: "How do you describe your gender?",
          required: true,
          options: [
            { value: "female", label: "Female" },
            { value: "male", label: "Male" },
            { value: "another", label: "Another description" },
            PREFER_NOT_TO_ANSWER,
          ],
        },
        {
          code: "B3",
          type: "single_choice",
          label: "What is your current main activity?",
          required: true,
          options: [
            { value: "public_sector", label: "Employed in the public sector" },
            { value: "private_sector", label: "Employed in the private sector" },
            { value: "self_employed", label: "Self-employed or operating a business" },
            { value: "student", label: "Student" },
            { value: "unemployed", label: "Unemployed and looking for work" },
            { value: "not_in_paid_employment", label: "Not currently in paid employment" },
            OTHER_OPTION,
            PREFER_NOT_TO_ANSWER,
          ],
        },
        {
          code: "B4",
          type: "single_choice",
          label: "What is the highest level of education you have completed?",
          required: true,
          options: [
            { value: "primary", label: "Primary education" },
            { value: "secondary", label: "Secondary education" },
            { value: "certificate_trade", label: "Certificate or trade qualification" },
            { value: "diploma", label: "Diploma" },
            { value: "bachelor", label: "Bachelor’s degree" },
            { value: "postgraduate", label: "Postgraduate qualification" },
            OTHER_OPTION,
            PREFER_NOT_TO_ANSWER,
          ],
        },
        {
          code: "B5",
          type: "multi_choice",
          label: "Which statement best describes your connection to Honiara?",
          helpText: "You may select more than one.",
          required: true,
          options: [
            { value: "live", label: "I live in Honiara" },
            { value: "work", label: "I work in Honiara" },
            { value: "study", label: "I study in Honiara" },
          ],
        },
      ],
    },
    {
      id: "C",
      title: "Section C: General Facebook Use",
      questions: [
        {
          code: "C1",
          type: "single_choice",
          label: "For approximately how long have you used Facebook?",
          required: true,
          options: [
            { value: "lt_1", label: "Less than 1 year" },
            { value: "1_2", label: "1–2 years" },
            { value: "3_5", label: "3–5 years" },
            { value: "6_10", label: "6–10 years" },
            { value: "gt_10", label: "More than 10 years" },
            { value: "not_sure", label: "Not sure" },
          ],
        },
        {
          code: "C2",
          type: "single_choice",
          label: "How often do you normally use Facebook?",
          required: true,
          options: [
            { value: "lt_weekly", label: "Less than once a week" },
            { value: "few_times_week", label: "A few times a week" },
            { value: "about_daily", label: "About once a day" },
            { value: "several_daily", label: "Several times a day" },
            { value: "almost_constantly", label: "Almost constantly throughout the day" },
          ],
        },
        {
          code: "C3",
          type: "single_choice",
          label: "On a typical day, approximately how much total time do you spend on Facebook?",
          required: true,
          options: [
            { value: "lt_30m", label: "Less than 30 minutes" },
            { value: "30m_1h", label: "30 minutes to less than 1 hour" },
            { value: "1h_2h", label: "1 to less than 2 hours" },
            { value: "2h_4h", label: "2 to less than 4 hours" },
            { value: "4h_plus", label: "4 hours or more" },
            { value: "not_sure", label: "Not sure" },
          ],
        },
        {
          code: "C4",
          type: "single_choice",
          label: "What device do you mainly use to access Facebook?",
          required: true,
          options: [
            { value: "smartphone", label: "Smartphone" },
            { value: "tablet", label: "Tablet" },
            { value: "laptop", label: "Laptop computer" },
            { value: "desktop", label: "Desktop computer" },
            { value: "shared_device", label: "Shared or borrowed device" },
            OTHER_OPTION,
          ],
        },
        {
          code: "C5",
          type: "multi_choice",
          label: "What are your main reasons for using Facebook?",
          helpText: "You may select more than one.",
          required: true,
          options: [
            { value: "family_friends", label: "Communicating with family and friends" },
            { value: "news", label: "News and current affairs" },
            { value: "community_info", label: "Community information" },
            { value: "entertainment", label: "Entertainment" },
            { value: "education", label: "Education or study" },
            { value: "employment_info", label: "Employment information" },
            { value: "buying", label: "Buying products or services" },
            { value: "selling", label: "Selling or promoting products or services" },
            { value: "tourism_info", label: "Tourism and travel information" },
            { value: "government_info", label: "Government information and public services" },
            { value: "religious", label: "Religious or church activities" },
            { value: "political", label: "Political information or discussion" },
            OTHER_OPTION,
          ],
        },
        {
          code: "C6",
          type: "matrix",
          label: "How often do you do the following on Facebook?",
          required: true,
          columns: FREQUENCY_COLUMNS,
          rows: [
            { value: "communicate", label: "Communicate with family or friends" },
            { value: "read_news", label: "Read news or public information" },
            { value: "participate_groups", label: "Participate in groups or community pages" },
            { value: "post_content", label: "Post, comment or share content" },
            { value: "buy_search", label: "Buy or search for products and services" },
            { value: "promote_sell", label: "Promote or sell products and services" },
            { value: "tourism_search", label: "Look for tourism or travel information" },
            { value: "government_access", label: "Access government information" },
          ],
        },
      ],
    },
    {
      id: "D",
      title: "Section D: Facebook, Business and Economic Activity",
      questions: [
        {
          code: "D1",
          type: "single_choice",
          label: "During the past 12 months, have you used Facebook to buy or search for a product or service?",
          required: true,
          options: yesNoNotSure(),
        },
        {
          code: "D2",
          type: "single_choice",
          label: "During the past 12 months, have you used Facebook to sell or promote a product or service?",
          required: true,
          options: yesNoNotSure(),
        },
        {
          code: "D3",
          type: "multi_choice",
          label: "What types of products or services have you bought, searched for, sold or promoted through Facebook?",
          helpText: "You may select more than one.",
          required: true,
          options: [
            { value: "food", label: "Food or catering" },
            { value: "clothing", label: "Clothing, jewellery or personal items" },
            { value: "household_goods", label: "Household goods" },
            { value: "transport", label: "Transport services" },
            { value: "accommodation", label: "Accommodation" },
            { value: "tourism_travel", label: "Tourism or travel services" },
            { value: "professional_services", label: "Professional or technical services" },
            { value: "agriculture_fisheries", label: "Agricultural or fisheries products" },
            { value: "employment_services", label: "Employment-related services or opportunities" },
            { value: "none", label: "I have not used Facebook for these purposes", exclusive: true },
            OTHER_OPTION,
          ],
        },
        {
          code: "D4",
          type: "multi_choice",
          label: "Before buying from a Facebook seller, what information do you normally consider?",
          helpText: "You may select more than one.",
          required: true,
          options: [
            { value: "price", label: "Price" },
            { value: "photos_description", label: "Product photographs or description" },
            { value: "comments_reviews", label: "Comments or reviews" },
            { value: "followers_activity", label: "Number of followers or page activity" },
            { value: "recommendation", label: "Recommendation from someone I know" },
            { value: "seller_reputation", label: "Seller’s identity or reputation" },
            { value: "payment_method", label: "Payment method" },
            { value: "delivery", label: "Delivery or collection arrangements" },
            { value: "do_not_buy", label: "I do not buy through Facebook", exclusive: true },
            OTHER_OPTION,
          ],
        },
        {
          code: "D5",
          type: "matrix",
          label: "Please indicate how much you agree or disagree with each statement.",
          required: true,
          columns: AGREE_COLUMNS_WITH_NA,
          rows: [
            { value: "easier_find", label: "Facebook makes it easier to find products and services in Honiara" },
            { value: "opportunities_small_business", label: "Facebook creates opportunities for small businesses and informal sellers" },
            { value: "helps_communicate_customers", label: "Facebook helps businesses communicate with customers" },
            { value: "info_reliable", label: "Information provided by Facebook sellers is generally reliable" },
            { value: "confident_buying", label: "I feel confident buying products or services advertised on Facebook" },
            { value: "difficult_resolve", label: "It is difficult to resolve problems when a Facebook transaction goes wrong" },
          ],
        },
        {
          code: "D6",
          type: "single_choice",
          label: "During the past 12 months, have you experienced or suspected a scam involving buying, selling or payment through Facebook?",
          required: true,
          options: yesNoNotSure([PREFER_NOT_TO_ANSWER]),
        },
        {
          code: "D7",
          type: "multi_choice",
          label: "If you experienced or suspected a Facebook-related scam, what action did you take?",
          helpText: "You may select more than one.",
          required: false,
          options: [
            { value: "reported_facebook", label: "Reported the account or post to Facebook" },
            { value: "reported_police", label: "Reported the matter to the police or another authority" },
            { value: "reported_bank", label: "Reported the matter to a bank or financial service provider" },
            { value: "warned_others", label: "Warned family, friends or the public" },
            { value: "contacted_party", label: "Contacted the seller or buyer" },
            { value: "took_no_action", label: "Took no action" },
            { value: "no_scam", label: "I have not experienced or suspected a scam", exclusive: true },
            OTHER_OPTION,
            PREFER_NOT_TO_ANSWER,
          ],
        },
      ],
    },
    {
      id: "E",
      title: "Section E: Facebook and Tourism",
      questions: [
        {
          code: "E1",
          type: "single_choice",
          label: "During the past 12 months, have you used Facebook to search for tourism or travel information?",
          required: true,
          options: yesNoNotSure(),
        },
        {
          code: "E2",
          type: "multi_choice",
          label: "What types of tourism or travel information have you looked for on Facebook?",
          helpText: "You may select more than one.",
          required: false,
          options: [
            { value: "accommodation", label: "Accommodation" },
            { value: "transport", label: "Transport" },
            { value: "restaurants", label: "Restaurants or food services" },
            { value: "attractions", label: "Tourist attractions or destinations" },
            { value: "cultural_events", label: "Cultural events or festivals" },
            { value: "travel_costs", label: "Travel costs" },
            { value: "safety_weather", label: "Safety or weather information" },
            { value: "reviews", label: "Reviews and recommendations" },
            { value: "none", label: "I have not searched for tourism information", exclusive: true },
            OTHER_OPTION,
          ],
        },
        {
          code: "E3",
          type: "single_choice",
          label: "Has information on Facebook influenced your decision to visit a destination, attend an event or purchase a tourism-related service?",
          required: true,
          options: [
            { value: "yes_significantly", label: "Yes, significantly" },
            { value: "yes_some_extent", label: "Yes, to some extent" },
            { value: "no", label: "No" },
            { value: "not_sure", label: "Not sure" },
            { value: "not_applicable", label: "Not applicable" },
          ],
        },
        {
          code: "E4",
          type: "matrix",
          label: "Please indicate how much you agree or disagree with each statement.",
          required: true,
          columns: AGREE_COLUMNS_WITH_NA,
          rows: [
            { value: "discover_destinations", label: "Facebook helps people discover tourism destinations in Solomon Islands" },
            { value: "useful_planning", label: "Facebook provides useful information for planning travel" },
            { value: "operators_promote", label: "Facebook helps tourism operators promote their services" },
            { value: "reviews_influence", label: "Reviews and recommendations on Facebook influence tourism decisions" },
            { value: "info_accurate", label: "Tourism information on Facebook is generally accurate and current" },
            { value: "misleading_damages_reputation", label: "Poor or misleading Facebook content can damage the reputation of a tourism business or destination" },
          ],
        },
      ],
    },
    {
      id: "F",
      title: "Section F: Facebook, Government Communication and Public Engagement",
      questions: [
        {
          code: "F1",
          type: "single_choice",
          label: "During the past 12 months, have you used Facebook to obtain information from a government ministry, agency, provincial government or public institution?",
          required: true,
          options: yesNoNotSure(),
        },
        {
          code: "F2",
          type: "multi_choice",
          label: "What types of government or public information have you accessed through Facebook?",
          helpText: "You may select more than one.",
          required: false,
          options: [
            { value: "public_health", label: "Public-health information" },
            { value: "disaster_emergency", label: "Weather, disaster or emergency information" },
            { value: "government_services", label: "Government services or procedures" },
            { value: "employment_scholarships", label: "Employment or scholarship opportunities" },
            { value: "public_notices", label: "Public notices or policy announcements" },
            { value: "police_safety", label: "Police or public-safety information" },
            { value: "community_consultations", label: "Community consultations or public meetings" },
            { value: "political_info", label: "Political information" },
            { value: "none", label: "I have not accessed government information", exclusive: true },
            OTHER_OPTION,
          ],
        },
        {
          code: "F3",
          type: "single_choice",
          label: "Have you ever used Facebook to communicate with, comment on or raise an issue with a government agency or public institution?",
          required: true,
          options: yesNoNotSure(),
        },
        {
          code: "F4",
          type: "single_choice",
          label: "If yes, did you receive a useful response?",
          required: false,
          options: [
            { value: "yes", label: "Yes" },
            { value: "partly", label: "Partly" },
            { value: "no", label: "No" },
            { value: "did_not_expect", label: "I did not expect a response" },
            { value: "not_applicable", label: "Not applicable" },
          ],
        },
        {
          code: "F5",
          type: "matrix",
          label: "Please indicate how much you agree or disagree with each statement.",
          required: true,
          columns: AGREE_COLUMNS_WITH_NA,
          rows: [
            { value: "agencies_communicate_quickly", label: "Facebook helps government agencies communicate quickly with the public" },
            { value: "pages_useful", label: "Government Facebook pages provide useful public information" },
            { value: "info_accurate", label: "Government information shared on Facebook is generally accurate" },
            { value: "easier_express_concerns", label: "Facebook makes it easier for citizens to express concerns about public issues" },
            { value: "should_respond_more", label: "Government agencies should respond more consistently to questions raised on Facebook" },
            { value: "misinformation_reduces_trust", label: "Misinformation on Facebook can reduce public trust in government institutions" },
          ],
        },
      ],
    },
    {
      id: "G",
      title: "Section G: Community Wellbeing, Safety and Responsible Use",
      questions: [
        {
          code: "G1",
          type: "matrix",
          label: "During the past 12 months, how often have you encountered the following on Facebook?",
          required: true,
          columns: FREQUENCY_COLUMNS_WITH_NOT_SURE,
          rows: [
            { value: "false_misleading", label: "Information that appeared false or misleading" },
            { value: "scams_ads", label: "Scams or suspicious advertisements" },
            { value: "bullying", label: "Insults, bullying or personal attacks" },
            { value: "conflict", label: "Arguments or conflict between individuals or groups" },
            { value: "private_info_disclosed", label: "Content that disclosed someone’s private information" },
            { value: "useful_warnings", label: "Useful warnings or community safety information" },
            { value: "support_requests", label: "Requests for community, church or family support" },
          ],
        },
        {
          code: "G2",
          type: "single_choice",
          label: "Before sharing important information on Facebook, how often do you check whether it is accurate?",
          required: true,
          options: [
            { value: "never", label: "Never" },
            { value: "rarely", label: "Rarely" },
            { value: "sometimes", label: "Sometimes" },
            { value: "often", label: "Often" },
            { value: "always", label: "Always" },
          ],
        },
        {
          code: "G3",
          type: "single_choice",
          label: "How confident are you in recognising false or misleading information on Facebook?",
          required: true,
          options: [
            { value: "not_confident", label: "Not confident at all" },
            { value: "slightly_confident", label: "Slightly confident" },
            { value: "moderately_confident", label: "Moderately confident" },
            { value: "very_confident", label: "Very confident" },
            { value: "completely_confident", label: "Completely confident" },
          ],
        },
        {
          code: "G4",
          type: "single_choice",
          label: "Do you know how to use Facebook’s privacy, blocking and reporting functions?",
          required: true,
          options: [
            { value: "know_all", label: "Yes, I know how to use all of them" },
            { value: "know_some", label: "Yes, I know how to use some of them" },
            { value: "heard_not_know", label: "I have heard of them but do not know how to use them" },
            { value: "no", label: "No" },
            { value: "not_sure", label: "Not sure" },
          ],
        },
        {
          code: "G5",
          type: "multi_choice",
          label: "During the past 12 months, has your use of Facebook contributed to any of the following?",
          helpText: "You may select more than one.",
          required: true,
          options: [
            { value: "connection_family", label: "Better connection with family or friends" },
            { value: "access_info", label: "Better access to useful information" },
            { value: "opportunities", label: "New business, employment or educational opportunities" },
            { value: "community_involvement", label: "Greater involvement in community activities" },
            { value: "learning_govt", label: "Learning about government services or public issues" },
            { value: "reduced_time_work_study", label: "Reduced time for work or study" },
            { value: "reduced_sleep", label: "Reduced sleep" },
            { value: "stress", label: "Stress, worry or emotional discomfort" },
            { value: "conflict", label: "Conflict with family, friends or other people" },
            { value: "financial_loss", label: "Financial loss or attempted financial loss" },
            { value: "none", label: "None of the above", exclusive: true },
            PREFER_NOT_TO_ANSWER,
            OTHER_OPTION,
          ],
        },
        {
          code: "G6",
          type: "matrix",
          label: "Please indicate how much you agree or disagree with each statement.",
          required: true,
          columns: AGREE_COLUMNS,
          rows: [
            { value: "strengthens_communication", label: "Facebook strengthens communication among families and communities" },
            { value: "support_emergencies", label: "Facebook helps people obtain support during emergencies or difficult situations" },
            { value: "unnecessary_conflict", label: "Facebook contributes to unnecessary conflict within communities" },
            { value: "affects_work_study", label: "Excessive Facebook use can negatively affect work, study or family responsibilities" },
            { value: "need_more_education", label: "People in Honiara need more education about online safety and responsible Facebook use" },
            { value: "overall_positive", label: "Facebook’s overall contribution to life in Honiara is positive" },
          ],
        },
        {
          code: "G7",
          type: "single_choice",
          label: "Overall, how would you describe Facebook’s effect on your own life?",
          required: true,
          options: [
            { value: "very_negative", label: "Very negative" },
            { value: "mostly_negative", label: "Mostly negative" },
            { value: "both", label: "Both positive and negative" },
            { value: "mostly_positive", label: "Mostly positive" },
            { value: "very_positive", label: "Very positive" },
            { value: "not_sure", label: "Not sure" },
          ],
        },
      ],
    },
    {
      id: "H",
      title: "Section H: Improvement and Recommendations",
      questions: [
        {
          code: "H1",
          type: "multi_choice",
          label: "Which actions would most improve Facebook use in Honiara?",
          helpText: "Please select up to three.",
          required: true,
          maxSelections: 3,
          options: [
            { value: "public_education", label: "More public education about online safety" },
            { value: "action_against_scams", label: "Stronger action against scams and fraudulent sellers" },
            { value: "better_checking", label: "Better checking of information before it is shared" },
            { value: "responsible_behaviour", label: "More responsible behaviour by Facebook users" },
            { value: "privacy_awareness", label: "Improved privacy awareness" },
            { value: "faster_reporting", label: "Faster reporting of harmful or illegal content" },
            { value: "accurate_govt_info", label: "More accurate and regular government information" },
            { value: "marketing_skills", label: "Better Facebook marketing skills for businesses" },
            { value: "digital_skills_tourism", label: "Better digital skills for tourism operators" },
            { value: "parental_guidance", label: "Greater parental and family guidance" },
            { value: "stronger_laws", label: "Stronger laws or enforcement relating to harmful online conduct" },
            OTHER_OPTION,
          ],
        },
        {
          code: "H2",
          type: "text",
          label: "In your view, what is the main benefit of Facebook use in Honiara?",
          required: false,
          multiline: true,
        },
        {
          code: "H3",
          type: "text",
          label: "In your view, what is the main problem or risk associated with Facebook use in Honiara?",
          required: false,
          multiline: true,
        },
        {
          code: "H4",
          type: "text",
          label: "What is one recommendation you would make for safer or more effective Facebook use in Honiara?",
          required: false,
          multiline: true,
        },
        {
          code: "H5",
          type: "text",
          label: "Is there anything else you would like to share?",
          required: false,
          multiline: true,
        },
      ],
    },
  ],
};
